version: '3.1'

networks:
  promnet:
    driver: bridge
  dbnet:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    networks:
      - promnet

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./prometheus:/prometheus
      - ./data/alertmanager:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    networks:
      - promnet

  node:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - promnet

  pushgateway:
    image: prom/pushgateway
    ports:
        - 9091:9091
    networks:
        - promnet   

  cadvisor:
    image: google/cadvisor
    ports:
      - 8080:8080
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock,readonly
      - /:/rootfs:ro
      - /sys:/sys:ro    
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run:/var/run:rw
      - /cgroup:/sys/fs/cgroup:ro 
    privileged: true
    networks:
      - promnet
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M

  collectd:
    image: prom/collectd-exporter
    ports:
      - 9103:9103
    restart: always
    networks:
      - promnet

  alerta:
    image: alerta/alerta-web
    ports:
      - 9080:8081
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=mongodb://db:27017/monitoring
      # - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io
      - PLUGINS=remote_ip,reject,heartbeat,blackout,prometheus
      - ALERTMANAGER_API_URL=http://alertmanager:9093
    restart: always
    networks:
      - promnet
      - dbnet

  db:
    image: mongo
    volumes:
      - ./data/mongodb:/data/db 
    restart: always
    networks:
      - dbnet

